package main

var testdata = `- id: 1
  tenant_id: 1
  external_id: "EXT001"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "田中"
  first_name: "太郎"
  last_name_kana: "たなか"
  first_name_kana: "たろう"
  phone_number: "08012345678"
  phone_number_serial: "1"
  email: "tanaka@gmail.com"
  sex: 1
  birth_date: 1995-01-01 00:00:00
  zip_code: "123-4567"
  address: "東京都渋谷区"
  city_code: "13"
  use_jp_bank: 1
  nearest_station: "渋谷駅"
  hobby: "スポーツ"
  allergy: "花粉"
  blood_type: 1
  emergency_contact_phone_number: "08087654321"
  emergency_contact_last_name: "田中"
  emergency_contact_first_name: "花子"
  emergency_contact_relation: "配偶者"
  emergency_contact_zip_code: "123-4567"
  emergency_contact_address: "東京都渋谷区"
  height: 170
  tops_size_id: 1
  bottoms_size_id: 2
  shoes_size: 25.5
  eyesight_right: 1.0
  eyesight_left: 1.0
  medical_history: "アトピー"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "東京"
  available_workdays_week: 5
  available_workdays_month: 20
  earliest_available_date: 2022-01-01
  desired_commute_time_minutes: 30
  overtime_max: 20
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前は営業職でした"
  skill_note: "TOEIC 800点"
  bank_code: "0001"
  bank_name: "三井住友銀行"
  bank_branch_code: "001"
  bank_branch_name: "渋谷支店"
  deposit_type_id: 1
  bank_account_number: "12345678"
  bank_account_name: "田中太郎"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 0
  marital_status: 0
  has_my_number_card: 1
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 0
  has_nail: 1
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 1
  note: "候補者に関する備考"
  applied_at: 2022-01-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "山田太郎"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE001"
  line_display_name: "tanaka"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 0
  job_delivery_disabled: 0
  free_delivery_disabled: 0
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 0
  last_updated_via_csv: 0
  created_at: 2022-01-01 12:00:00
  updated_at: 2022-01-01 12:00:00
- id: 2
  tenant_id: 2
  external_id: "EXT002"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "山田"
  first_name: "花子"
  last_name_kana: "やまだ"
  first_name_kana: "はなこ"
  phone_number: "08023456789"
  phone_number_serial: "1"
  email: "yamada@gmail.com"
  sex: 2
  birth_date: 1990-02-02 00:00:00
  zip_code: "234-5678"
  address: "東京都新宿区"
  city_code: "13"
  use_jp_bank: 0
  nearest_station: "新宿駅"
  hobby: "音楽鑑賞"
  allergy: "なし"
  blood_type: 2
  emergency_contact_phone_number: "08076543210"
  emergency_contact_last_name: "山田"
  emergency_contact_first_name: "太郎"
  emergency_contact_relation: "配偶者"
  emergency_contact_zip_code: "234-5678"
  emergency_contact_address: "東京都新宿区"
  height: 160
  tops_size_id: 2
  bottoms_size_id: 3
  shoes_size: 23.0
  eyesight_right: 0.5
  eyesight_left: 0.5
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "新宿"
  available_workdays_week: 4
  available_workdays_month: 15
  earliest_available_date: 2022-02-01
  desired_commute_time_minutes: 45
  overtime_max: 10
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前は事務職でした"
  skill_note: "英検2級"
  bank_code: "0002"
  bank_name: "三菱UFJ銀行"
  bank_branch_code: "002"
  bank_branch_name: "新宿支店"
  deposit_type_id: 2
  bank_account_number: "87654321"
  bank_account_name: "山田花子"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 1
  marital_status: 1
  has_my_number_card: 0
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 1
  has_nail: 0
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 2
  note: "候補者に関する備考"
  applied_at: 2022-02-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "親族"
  referrer_name: "佐藤次郎"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE002"
  line_display_name: "yamada"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 0
  job_delivery_disabled: 0
  free_delivery_disabled: 0
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 0
  last_updated_via_csv: 0
  created_at: 2022-02-01 12:00:00
  updated_at: 2022-02-01 12:00:00
- id: 3
  tenant_id: 3
  external_id: "EXT003"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "鈴木"
  first_name: "健太"
  last_name_kana: "すずき"
  first_name_kana: "けんた"
  phone_number: "08034567890"
  phone_number_serial: "1"
  email: "suzuki@gmail.com"
  sex: 1
  birth_date: 1992-03-03 00:00:00
  zip_code: "345-6789"
  address: "東京都千代田区"
  city_code: "13"
  use_jp_bank: 1
  nearest_station: "秋葉原駅"
  hobby: "読書"
  allergy: "ペットの毛"
  blood_type: 3
  emergency_contact_phone_number: "08098765432"
  emergency_contact_last_name: "鈴木"
  emergency_contact_first_name: "さくら"
  emergency_contact_relation: "兄妹"
  emergency_contact_zip_code: "345-6789"
  emergency_contact_address: "東京都千代田区"
  height: 180
  tops_size_id: 3
  bottoms_size_id: 4
  shoes_size: 26.0
  eyesight_right: 2.0
  eyesight_left: 2.0
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "千代田区"
  available_workdays_week: 3
  available_workdays_month: 10
  earliest_available_date: 2022-03-01
  desired_commute_time_minutes: 60
  overtime_max: 5
  holiday_workable: 0
  desired_note: "希望についての備考"
  employed: 0
  career_note: "以前は学生でした"
  skill_note: "Photoshopでの画像編集"
  bank_code: "0003"
  bank_name: "みずほ銀行"
  bank_branch_code: "003"
  bank_branch_name: "秋葉原支店"
  deposit_type_id: 3
  bank_account_number: "76543210"
  bank_account_name: "鈴木健太"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 2
  marital_status: 1
  has_my_number_card: 1
  has_pension_book: 0
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 0
  salary_insurance_note: "社会保険未加入"
  family_note: "家族についての備考"
  has_tattoo: 0
  has_nail: 1
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 3
  note: "候補者に関する備考"
  applied_at: 2022-03-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "佐々木三郎"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE003"
  line_display_name: "suzuki"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 1
  job_delivery_disabled: 1
  free_delivery_disabled: 0
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 0
  last_updated_via_csv: 0
  created_at: 2022-03-01 12:00:00
  updated_at: 2022-03-01 12:00:00
- id: 4
  tenant_id: 1
  external_id: "EXT004"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "佐藤"
  first_name: "芳子"
  last_name_kana: "さとう"
  first_name_kana: "よしこ"
  phone_number: "08098765432"
  phone_number_serial: "2"
  email: "sato@gmail.com"
  sex: 2
  birth_date: 1988-04-04 00:00:00
  zip_code: "456-7890"
  address: "東京都千代田区"
  city_code: "13"
  use_jp_bank: 1
  nearest_station: "東京駅"
  hobby: "旅行"
  allergy: "花粉"
  blood_type: 4
  emergency_contact_phone_number: "08087654321"
  emergency_contact_last_name: "佐藤"
  emergency_contact_first_name: "太郎"
  emergency_contact_relation: "兄弟"
  emergency_contact_zip_code: "456-7890"
  emergency_contact_address: "東京都千代田区"
  height: 165
  tops_size_id: 4
  bottoms_size_id: 5
  shoes_size: 24.5
  eyesight_right: 1.5
  eyesight_left: 1.5
  medical_history: "アレルギー性鼻炎"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "千代田区"
  available_workdays_week: 2
  available_workdays_month: 8
  earliest_available_date: 2022-04-01
  desired_commute_time_minutes: 90
  overtime_max: 0
  holiday_workable: 0
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前は販売職でした"
  skill_note: "Word、Excel操作"
  bank_code: "0004"
  bank_name: "りそな銀行"
  bank_branch_code: "004"
  bank_branch_name: "東京支店"
  deposit_type_id: 4
  bank_account_number: "23456789"
  bank_account_name: "佐藤芳子"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 3
  marital_status: 0
  has_my_number_card: 0
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 0
  has_nail: 1
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 1
  note: "候補者に関する備考"
  applied_at: 2022-04-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "伊藤直子"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE004"
  line_display_name: "sato"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 0
  job_delivery_disabled: 1
  free_delivery_disabled: 1
  creation_method: 1
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 1
  last_updated_via_csv: 1
  created_at: 2022-04-01 12:00:00
  updated_at: 2022-04-01 12:00:00
- id: 5
  tenant_id: 2
  external_id: "EXT005"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "高橋"
  first_name: "雅弘"
  last_name_kana: "たかはし"
  first_name_kana: "まさひろ"
  phone_number: "08023456789"
  phone_number_serial: "2"
  email: "takahashi@gmail.com"
  sex: 1
  birth_date: 1995-05-05 00:00:00
  zip_code: "567-8901"
  address: "東京都新宿区"
  city_code: "13"
  use_jp_bank: 0
  nearest_station: "新宿駅"
  hobby: "ゲーム"
  allergy: "なし"
  blood_type: 1
  emergency_contact_phone_number: "08076543210"
  emergency_contact_last_name: "高橋"
  emergency_contact_first_name: "芳恵"
  emergency_contact_relation: "配偶者"
  emergency_contact_zip_code: "567-8901"
  emergency_contact_address: "東京都新宿区"
  height: 175
  tops_size_id: 5
  bottoms_size_id: 6
  shoes_size: 26.5
  eyesight_right: 1.0
  eyesight_left: 1.0
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "新宿"
  available_workdays_week: 1
  available_workdays_month: 5
  earliest_available_date: 2022-05-01
  desired_commute_time_minutes: 30
  overtime_max: 15
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 0
  career_note: "以前は学生でした"
  skill_note: "Excelのマクロ操作"
  bank_code: "0005"
  bank_name: "ゆうちょ銀行"
  bank_branch_code: "005"
  bank_branch_name: "新宿中央支店"
  deposit_type_id: 5
  bank_account_number: "34567890"
  bank_account_name: "高橋雅弘"
  jp_bank_deposit_type: 1
  jp_bank_branch_name: "新宿中央支店"
  jp_bank_code: "000"
  jp_bank_number: "1234567"
  jp_bank_account_name: "タカハシマサヒロ"
  account_note: "口座に関する備考"
  num_dependents: 0
  marital_status: 0
  has_my_number_card: 1
  has_pension_book: 0
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 0
  has_nail: 1
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 2
  note: "候補者に関する備考"
  applied_at: 2022-05-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "木村直子"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE005"
  line_display_name: "takahashi"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 0
  job_delivery_disabled: 1
  free_delivery_disabled: 0
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 1
  last_updated_via_csv: 1
  created_at: 2022-05-01 12:00:00
  updated_at: 2022-05-01 12:00:00
- id: 6
  tenant_id: 3
  external_id: "EXT006"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "伊藤"
  first_name: "直子"
  last_name_kana: "いとう"
  first_name_kana: "なおこ"
  phone_number: "08034567890"
  phone_number_serial: "2"
  email: "ito@gmail.com"
  sex: 2
  birth_date: 1990-06-06 00:00:00
  zip_code: "678-9012"
  address: "東京都新宿区"
  city_code: "13"
  use_jp_bank: 0
  nearest_station: "新宿駅"
  hobby: "料理"
  allergy: "シェルフィッシュ"
  blood_type: 2
  emergency_contact_phone_number: "08098765432"
  emergency_contact_last_name: "伊藤"
  emergency_contact_first_name: "直行"
  emergency_contact_relation: "兄弟"
  emergency_contact_zip_code: "678-9012"
  emergency_contact_address: "東京都新宿区"
  height: 160
  tops_size_id: 6
  bottoms_size_id: 7
  shoes_size: 23.5
  eyesight_right: 0.5
  eyesight_left: 0.5
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "新宿"
  available_workdays_week: 2
  available_workdays_month: 8
  earliest_available_date: 2022-06-01
  desired_commute_time_minutes: 45
  overtime_max: 10
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前は事務職でした"
  skill_note: "英検2級"
  bank_code: "0006"
  bank_name: "三井住友銀行"
  bank_branch_code: "006"
  bank_branch_name: "新宿支店"
  deposit_type_id: 6
  bank_account_number: "87654321"
  bank_account_name: "伊藤直子"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 1
  marital_status: 1
  has_my_number_card: 0
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 1
  has_nail: 0
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 3
  note: "候補者に関する備考"
  applied_at: 2022-06-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "佐々木三郎"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE006"
  line_display_name: "ito"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 1
  job_delivery_disabled: 1
  free_delivery_disabled: 0
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 0
  last_updated_via_csv: 0
  created_at: 2022-06-01 12:00:00
  updated_at: 2022-06-01 12:00:00
- id: 7
  tenant_id: 1
  external_id: "EXT007"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "山口"
  first_name: "隆"
  last_name_kana: "やまぐち"
  first_name_kana: "たかし"
  phone_number: "08087654321"
  phone_number_serial: "3"
  email: "yamaguchi@gmail.com"
  sex: 1
  birth_date: 1992-07-07 00:00:00
  zip_code: "789-0123"
  address: "東京都渋谷区"
  city_code: "13"
  use_jp_bank: 0
  nearest_station: "渋谷駅"
  hobby: "サッカー"
  allergy: "なし"
  blood_type: 3
  emergency_contact_phone_number: "08098765432"
  emergency_contact_last_name: "山口"
  emergency_contact_first_name: "絵美"
  emergency_contact_relation: "姉弟"
  emergency_contact_zip_code: "789-0123"
  emergency_contact_address: "東京都渋谷区"
  height: 180
  tops_size_id: 7
  bottoms_size_id: 8
  shoes_size: 27.5
  eyesight_right: 2.0
  eyesight_left: 2.0
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "渋谷区"
  available_workdays_week: 3
  available_workdays_month: 12
  earliest_available_date: 2022-07-01
  desired_commute_time_minutes: 30
  overtime_max: 10
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前は営業職でした"
  skill_note: "TOEIC 800点"
  bank_code: "0007"
  bank_name: "三菱UFJ銀行"
  bank_branch_code: "007"
  bank_branch_name: "渋谷支店"
  deposit_type_id: 7
  bank_account_number: "23456789"
  bank_account_name: "山口隆"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 2
  marital_status: 1
  has_my_number_card: 0
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 0
  has_nail: 1
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 1
  note: "候補者に関する備考"
  applied_at: 2022-07-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "知人"
  referrer_name: "森田忠司"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE007"
  line_display_name: "yamaguchi"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 1
  job_delivery_disabled: 0
  free_delivery_disabled: 1
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 1
  last_updated_via_csv: 1
  created_at: 2022-07-01 12:00:00
  updated_at: 2022-07-01 12:00:00
- id: 8
  tenant_id: 2
  external_id: "EXT008"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "田村"
  first_name: "美智子"
  last_name_kana: "たむら"
  first_name_kana: "みちこ"
  phone_number: "08034567890"
  phone_number_serial: "3"
  email: "tamura@gmail.com"
  sex: 2
  birth_date: 1990-08-08 00:00:00
  zip_code: "890-1234"
  address: "東京都渋谷区"
  city_code: "13"
  use_jp_bank: 1
  nearest_station: "渋谷駅"
  hobby: "カフェ巡り"
  allergy: "なし"
  blood_type: 2
  emergency_contact_phone_number: "08087654321"
  emergency_contact_last_name: "田村"
  emergency_contact_first_name: "健太"
  emergency_contact_relation: "兄弟"
  emergency_contact_zip_code: "890-1234"
  emergency_contact_address: "東京都渋谷区"
  height: 160
  tops_size_id: 8
  bottoms_size_id: 9
  shoes_size: 23.5
  eyesight_right: 1.0
  eyesight_left: 1.0
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "渋谷区"
  available_workdays_week: 2
  available_workdays_month: 8
  earliest_available_date: 2022-08-01
  desired_commute_time_minutes: 30
  overtime_max: 10
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前はクリエイティブ職でした"
  skill_note: "Illustrator、Photoshop"
  bank_code: "0008"
  bank_name: "三井住友銀行"
  bank_branch_code: "008"
  bank_branch_name: "渋谷支店"
  deposit_type_id: 8
  bank_account_number: "23456789"
  bank_account_name: "田村美智子"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 2
  marital_status: 1
  has_my_number_card: 0
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 0
  has_nail: 1
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 2
  note: "候補者に関する備考"
  applied_at: 2022-08-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "佐々木三郎"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE008"
  line_display_name: "tamura"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 1
  job_delivery_disabled: 1
  free_delivery_disabled: 0
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 1
  last_updated_via_csv: 1
  created_at: 2022-08-01 12:00:00
  updated_at: 2022-08-01 12:00:00
- id: 9
  tenant_id: 3
  external_id: "EXT009"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "三浦"
  first_name: "大樹"
  last_name_kana: "みうら"
  first_name_kana: "たいき"
  phone_number: "08023456789"
  phone_number_serial: "3"
  email: "miura@gmail.com"
  sex: 1
  birth_date: 1995-09-09 00:00:00
  zip_code: "901-2345"
  address: "東京都新宿区"
  city_code: "13"
  use_jp_bank: 0
  nearest_station: "新宿駅"
  hobby: "スポーツ観戦"
  allergy: "なし"
  blood_type: 1
  emergency_contact_phone_number: "08076543210"
  emergency_contact_last_name: "三浦"
  emergency_contact_first_name: "美樹"
  emergency_contact_relation: "配偶者"
  emergency_contact_zip_code: "901-2345"
  emergency_contact_address: "東京都新宿区"
  height: 170
  tops_size_id: 9
  bottoms_size_id: 10
  shoes_size: 25.0
  eyesight_right: 1.0
  eyesight_left: 1.0
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "新宿"
  available_workdays_week: 2
  available_workdays_month: 8
  earliest_available_date: 2022-09-01
  desired_commute_time_minutes: 45
  overtime_max: 10
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前は事務職でした"
  skill_note: "英検2級"
  bank_code: "0009"
  bank_name: "三菱UFJ銀行"
  bank_branch_code: "009"
  bank_branch_name: "新宿支店"
  deposit_type_id: 9
  bank_account_number: "76543210"
  bank_account_name: "三浦大樹"
  jp_bank_deposit_type: null
  jp_bank_branch_name: null
  jp_bank_code: null
  jp_bank_number: null
  jp_bank_account_name: null
  account_note: "口座に関する備考"
  num_dependents: 3
  marital_status: 1
  has_my_number_card: 0
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 0
  has_nail: 1
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 3
  note: "候補者に関する備考"
  applied_at: 2022-09-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "佐々木三郎"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE009"
  line_display_name: "miura"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 0
  job_delivery_disabled: 0
  free_delivery_disabled: 1
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 1
  last_updated_via_csv: 1
  created_at: 2022-09-01 12:00:00
  updated_at: 2022-09-01 12:00:00
- id: 10
  tenant_id: 1
  external_id: "EXT010"
  integration_inbound_id: null
  integration_outbound_id: null
  last_name: "木村"
  first_name: "次郎"
  last_name_kana: "きむら"
  first_name_kana: "じろう"
  phone_number: "08087654321"
  phone_number_serial: "4"
  email: "kimura@gmail.com"
  sex: 1
  birth_date: 1995-10-10 00:00:00
  zip_code: "012-3456"
  address: "東京都新宿区"
  city_code: "13"
  use_jp_bank: 1
  nearest_station: "新宿駅"
  hobby: "ゴルフ"
  allergy: "なし"
  blood_type: 2
  emergency_contact_phone_number: "08098765432"
  emergency_contact_last_name: "木村"
  emergency_contact_first_name: "次子"
  emergency_contact_relation: "姉弟"
  emergency_contact_zip_code: "012-3456"
  emergency_contact_address: "東京都新宿区"
  height: 175
  tops_size_id: 10
  bottoms_size_id: 1
  shoes_size: 26.5
  eyesight_right: 1.5
  eyesight_left: 1.5
  medical_history: "なし"
  personal_note: "特になし"
  desired_hourly_pay: null
  desired_daily_pay: null
  desired_payment_type_id: null
  desired_work_time_start_at: null
  desired_work_time_end_at: null
  desired_work_place: "新宿"
  available_workdays_week: 3
  available_workdays_month: 12
  earliest_available_date: 2022-10-01
  desired_commute_time_minutes: 45
  overtime_max: 10
  holiday_workable: 1
  desired_note: "希望についての備考"
  employed: 1
  career_note: "以前はIT職でした"
  skill_note: "プログラミング経験あり"
  bank_code: "0010"
  bank_name: "ゆうちょ銀行"
  bank_branch_code: "010"
  bank_branch_name: "新宿中央支店"
  deposit_type_id: 10
  bank_account_number: "23456789"
  bank_account_name: "木村次郎"
  jp_bank_deposit_type: 1
  jp_bank_branch_name: "新宿中央支店"
  jp_bank_code: "123"
  jp_bank_number: "4567890"
  jp_bank_account_name: "キムラジロウ"
  account_note: "口座に関する備考"
  num_dependents: 3
  marital_status: 1
  has_my_number_card: 0
  has_pension_book: 1
  has_employment_insurance_certificate: 1
  has_disability_certificate: 0
  has_social_insurance: 1
  salary_insurance_note: "社会保険加入済み"
  family_note: "家族についての備考"
  has_tattoo: 1
  has_nail: 0
  interview_note: "面接時のメモ"
  document_note: "書類に関する備考"
  branch_id: 1
  note: "候補者に関する備考"
  applied_at: 2022-10-01 12:00:00
  application_method_id: null
  application_media_id: null
  applied_job_id: null
  applied_job_questionnaire: "志望動機について"
  applied_external_job_name: ""
  referrer_relation: "友人"
  referrer_name: "佐々木三郎"
  strong_point: "コミュニケーション能力"
  interview_evaluation: "面接の評価"
  candidate_note: "候補者に関する備考"
  consented: 1
  line_user_id: "LINE010"
  line_display_name: "kimura"
  line_display_nickname: ""
  line_picture_url: "https://example.com/picture.jpg"
  line_note: "LINEに関する備考"
  delivery_optout: 1
  job_delivery_disabled: 0
  free_delivery_disabled: 1
  creation_method: 0
  latest_action_step_id: null
  memo: "メモ"
  confirmed: 1
  last_updated_via_csv: 1
  created_at: 2022-10-01 12:00:00
  updated_at: 2022-10-01 12:00:00`
